# Generated by Django 2.2.6 on 2019-11-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='descripcion',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
