# Generated by Django 2.2.6 on 2019-11-08 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_galeria'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Galeria',
            new_name='GL',
        ),
        migrations.RenameField(
            model_name='gl',
            old_name='galeria',
            new_name='foto',
        ),
    ]
