# Generated by Django 2.2.6 on 2019-11-08 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191108_0104'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GL',
        ),
    ]
