# Generated by Django 2.2.6 on 2019-11-13 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_mv'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MV',
            new_name='Mision',
        ),
    ]
