# Generated by Django 2.2.6 on 2019-11-13 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191113_0034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mision',
        ),
    ]
