# Generated by Django 2.2.6 on 2019-11-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_mision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mision',
            name='descripcion',
            field=models.CharField(max_length=1000),
        ),
    ]
